"""
Django settings for marine_tracker project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

DEBUG = config('DEBUG', default=False, cast=bool)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+)sa2fn-12qlqt#g%m(#eoz0t%adbyxx4urxg@3d2hk@&0z5%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'vessel_api',
    'port_api',
    'lighthouse_api',
    'fleet_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marine_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marine_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'marine_tracker_db',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only
# For production, specify allowed origins:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]

# Rest Framework settings
REST_FRAMEWORK = {
#   'DEFAULT_PAGINATION_CLASS': None,  
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 500,
}

# Global Fishing Watch API token
GFW_API_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtpZEtleSJ9.eyJkYXRhIjp7Im5hbWUiOiJQYWxhayBDaGFuZGFrIiwidXNlcklkIjo0NDY3OCwiYXBwbGljYXRpb25OYW1lIjoiUGFsYWsgQ2hhbmRhayIsImlkIjoyNTM1LCJ0eXBlIjoidXNlci1hcHBsaWNhdGlvbiJ9LCJpYXQiOjE3NDQyNzExOTQsImV4cCI6MjA1OTYzMTE5NCwiYXVkIjoiZ2Z3IiwiaXNzIjoiZ2Z3In0.QeAW4548ONN-uMGsxBArxxC7zB-oA7XzvOsC2GWbHTyDzO8ICv_-B3wdqOSAV67BsmIUx8jmV0-RUg9Z2ZgTsGmnP5Nz4kzo5RcsmT8WzUB5pkjlrpQRpr6MdERrWHjKHxnT2LJbwGPxdnN5VgGGlYXw92DfdONfnb9Fdx54SFcvtxppGcO3h30KHr9Ct_NeliFBIzxXanYiUmF_UcA3ghDZ2MwzBQD96cT_7N9qu3Jv2hNjkOm_OWA5EdDWixd5NmDN9MLiDHt5JcZCC-3iCRMHd1j9TBhpz5A_GwW1Z3RlLP0haBqFiV0gvlztYM2iGu8bvJpvDoPK9goFwN187PrajSga7UsgtPITdZc18r5XsI_gpzJr1alv5keq02OJMJWsct3h88qXmgdNIaVD9K_XCZ3WBcb8BeGINpyiU5YKA2g2P9SDPKhNVoIR1M5EyTi85IqsI7jJPPDr3BgD0X0U_ipANtVIyxgLFvhYhmJ4fGoad19tkRDb34UuemHu"