# Generated by Django 5.2 on 2025-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesselposition',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='vessel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
