# Generated by Django 5.2 on 2025-05-22 07:38

from django.db import migrations, models

def create_default_offset(apps, schema_editor):
    PositionOffset = apps.get_model('vessel_api', 'PositionOffset')
    PositionOffset.objects.update_or_create(
        pk=1,
        defaults={'name': 'position_offset', 'value': 0.0}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vessel_api', '0002_alter_vesselposition_options_alter_vessel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='position_offset', max_length=100)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RunPython(create_default_offset),
    ]
