# Generated by Django 5.2 on 2025-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyLighthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Lighthouse',
        ),
    ]
