# Generated by Django 5.2 on 2025-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_api', '0003_lighthouse_delete_dummylighthouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lighthouse',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='lighthouse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lighthouse',
            name='height',
        ),
        migrations.RemoveField(
            model_name='lighthouse',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='lighthouse',
            name='year_built',
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
