# Generated by Django 5.2 on 2025-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_api', '0004_alter_lighthouse_options_remove_lighthouse_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lighthouse',
            options={},
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='entry_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
