# Generated by Django 5.2 on 2025-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_api', '0005_alter_lighthouse_options_lighthouse_entry_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lighthouse',
            old_name='website',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='lighthouse',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
