# Generated by Django 5.2 on 2025-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_api', '0006_rename_website_lighthouse_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyLighthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
